# Generated by Django 2.0.2 on 2018-02-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='tags',
            field=models.ManyToManyField(to='meshine_api.Tag'),
        ),
    ]
