# Generated by Django 2.0.2 on 2018-04-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0002_auto_20180408_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='tag_category',
            field=models.ManyToManyField(default=[], to='meshine_api.TagCategory'),
        ),
    ]
