# Generated by Django 2.0.1 on 2018-01-08 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0002_auto_20180107_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='summary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meshine_api.Summary'),
            preserve_default=False,
        ),
    ]
