# Generated by Django 2.0.2 on 2018-02-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0003_auto_20180228_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='summaries', to='meshine_api.Tag'),
        ),
    ]
