# Generated by Django 2.0.1 on 2018-01-08 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0003_object_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='members',
            field=models.ManyToManyField(through='meshine_api.UserProfileSummary', to=settings.AUTH_USER_MODEL),
        ),
    ]
