# Generated by Django 2.0.2 on 2018-04-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0003_auto_20180409_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsummary',
            name='main_question',
            field=models.BooleanField(default=False),
        ),
    ]
