# Generated by Django 2.0.1 on 2018-01-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0004_summary_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilesummary',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='userprofilesummary',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='members',
        ),
        migrations.DeleteModel(
            name='UserProfileSummary',
        ),
    ]
