# Generated by Django 2.0.1 on 2018-01-09 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0005_auto_20180109_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_author', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meshine_api.Summary')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='userProfileSummary',
            field=models.ManyToManyField(through='meshine_api.UserProfileSummary', to=settings.AUTH_USER_MODEL),
        ),
    ]
