# Generated by Django 2.0.2 on 2018-04-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0005_questionsummary_is_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsummary',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionSummaries', to='meshine_api.Question'),
        ),
        migrations.AlterField(
            model_name='questionsummary',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionSummaries', to='meshine_api.Summary'),
        ),
    ]
