# Generated by Django 2.0.2 on 2018-03-12 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0007_auto_20180312_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilesummary',
            name='last_modified_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
