# Generated by Django 2.0.2 on 2018-04-13 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0008_auto_20180411_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsummary',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meshine_api.Question'),
        ),
        migrations.AlterField(
            model_name='questionsummary',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meshine_api.Summary'),
        ),
    ]
