# Generated by Django 2.0.2 on 2018-04-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0009_auto_20180413_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
