# Generated by Django 2.0.2 on 2018-04-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0011_auto_20180414_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='questions',
            field=models.ManyToManyField(default=[], through='meshine_api.QuestionSummary', to='meshine_api.Question'),
        ),
    ]
