# Generated by Django 2.0.2 on 2018-04-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0012_auto_20180415_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='cover_image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
