# Generated by Django 2.0.2 on 2018-07-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0015_summary_validation_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
