# Generated by Django 2.0.2 on 2019-09-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0018_auto_20190915_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='location',
            new_name='content',
        ),
    ]
