# Generated by Django 2.0.2 on 2019-11-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0019_auto_20190915_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='info',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(unique=True, upload_to='userCreations/userName/gallery/'),
        ),
    ]
