# Generated by Django 2.0.2 on 2019-11-18 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0020_auto_20191102_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='info',
        ),
        migrations.AddField(
            model_name='file',
            name='additional_content',
            field=models.FileField(default=django.utils.timezone.now, upload_to='userCreations/userName/file/'),
            preserve_default=False,
        ),
    ]
