# Generated by Django 2.0.2 on 2019-11-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meshine_api', '0021_auto_20191118_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='additional_content',
            field=models.FileField(default='userCreations/userName/gallery/1.JPG', upload_to='userCreations/userName/file/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(default='userCreations/userName/gallery/1.JPG', upload_to='userCreations/userName/gallery/'),
        ),
    ]
